sudo: required
services:
  - docker

before_install:
  - docker build -t samuvain/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run samuvain/react-test npm test -- --coverage

after_success:
  - docker build -t samuvain/multi-client ./client
  - docker build -t samuvain/multi-nginx ./nginx
  - docker build -t samuvain/multi-server ./server
  - docker build -t samuvain/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push samuvain/multi-client
  - docker push samuvain/multi-nginx
  - docker push samuvain/multi-server
  - docker push samuvain/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-509621596342
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY